---
driver:
  name: vagrant
  synced_folders:
    - ["./chef-pkgs", "/tmp/chef-pkgs"]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: 13.3.42
  chef_omnibus_url: file:///tmp/chef-pkgs/install.sh

verifier:
  name: inspec

platforms:
  - name: sbeliakou/centos-7.3-x86_64-minimal

suites:
  - name: default
    run_list:
      - recipe[vim::default]
      - recipe[netstat::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
